@echo off
echo Iniciando processo de padronização de páginas HTML...
powershell -ExecutionPolicy Bypass -File "%~dp0padronizar-paginas.ps1"
echo.
echo Processo finalizado! Pressione qualquer tecla para sair...
pause > nul
